# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Momchil Hardalov
tagline:          'Sofia University'
description:      'PhD Student'
url:              http://mhardalov.github.io/
baseurl:          ''

author:
  name:           'Momchil Hardalov'


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mhardalov
